/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registration;

import conexion.conectate;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class View_User_Registration extends javax.swing.JFrame {

    conectate con = new conectate();
    CallableStatement cst;
    ResultSet r;
    Statement setencia;
    
    public View_User_Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        TextField_Nombre_Usuario_Registro = new javax.swing.JTextField();
        TextField_Apellido_Paterno_Usuario_Registro = new javax.swing.JTextField();
        TextField_Apellido_Materno_Usuario_Registro = new javax.swing.JTextField();
        TextField_Alias_Usuario_Registro = new javax.swing.JTextField();
        TextField_Cedula_Usuario_Registro = new javax.swing.JTextField();
        TextField_Direccion_Usuario_Registro = new javax.swing.JTextField();
        TextField_Telefono_Usuario_Registro = new javax.swing.JTextField();
        TextField_Password_Usuario_Registro = new javax.swing.JTextField();
        btn_Aceptar_Usuario_Registro = new javax.swing.JButton();
        lbl_Nombre = new javax.swing.JLabel();
        lbl_Apellido_Paterno = new javax.swing.JLabel();
        lbl_Apellido_Materno = new javax.swing.JLabel();
        lbl_Alias = new javax.swing.JLabel();
        lbl_Cedula = new javax.swing.JLabel();
        lbl_Direccion = new javax.swing.JLabel();
        lbl_Telefono = new javax.swing.JLabel();
        lbl_Password = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextField_Correo_Registro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextField_Tipo_Participante_Registro = new javax.swing.JTextField();

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextField_Nombre_Usuario_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Nombre_Usuario_RegistroActionPerformed(evt);
            }
        });

        TextField_Direccion_Usuario_Registro.setToolTipText("");

        btn_Aceptar_Usuario_Registro.setText("Aceptar");
        btn_Aceptar_Usuario_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Aceptar_Usuario_RegistroActionPerformed(evt);
            }
        });

        lbl_Nombre.setText("Nombre");

        lbl_Apellido_Paterno.setText("Apellido Paterno");

        lbl_Apellido_Materno.setText("Apellido Materno");

        lbl_Alias.setText("Alias");

        lbl_Cedula.setText("Cedula");

        lbl_Direccion.setText("Direccion");

        lbl_Telefono.setText("Telefono");

        lbl_Password.setText("Password");

        jLabel1.setText("Correo");

        jLabel2.setText("Tipo de Participante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Alias)
                    .addComponent(lbl_Cedula)
                    .addComponent(lbl_Direccion)
                    .addComponent(lbl_Telefono)
                    .addComponent(lbl_Password)
                    .addComponent(lbl_Nombre)
                    .addComponent(lbl_Apellido_Paterno)
                    .addComponent(lbl_Apellido_Materno)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextField_Apellido_Materno_Usuario_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(TextField_Apellido_Paterno_Usuario_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(TextField_Nombre_Usuario_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(btn_Aceptar_Usuario_Registro)
                    .addComponent(TextField_Alias_Usuario_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(TextField_Cedula_Usuario_Registro)
                    .addComponent(TextField_Direccion_Usuario_Registro)
                    .addComponent(TextField_Telefono_Usuario_Registro)
                    .addComponent(TextField_Password_Usuario_Registro)
                    .addComponent(TextField_Correo_Registro)
                    .addComponent(TextField_Tipo_Participante_Registro))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nombre)
                    .addComponent(TextField_Nombre_Usuario_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Apellido_Paterno)
                    .addComponent(TextField_Apellido_Paterno_Usuario_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Apellido_Materno)
                    .addComponent(TextField_Apellido_Materno_Usuario_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TextField_Correo_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_Alias_Usuario_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Alias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_Cedula_Usuario_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Cedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextField_Direccion_Usuario_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Direccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextField_Telefono_Usuario_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Telefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_Password_Usuario_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Password))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_Tipo_Participante_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_Aceptar_Usuario_Registro)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Aceptar_Usuario_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Aceptar_Usuario_RegistroActionPerformed
                //SE VALIDAN LOS CAMPOS DE TEXTO ANTES DE SER GUARDADOS PARA VER SI ALGUNO DE ELLOS ESTAN VACIOS, SI ASI FUESE MUESTRA
        //UN MENSAJE CORRESPONDIENTE AL CAMPO QUE ESTA SIN LLENAR
        if (this.TextField_Tipo_Participante_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL TIPO DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Tipo_Participante_Registro.requestFocus();
        } else if (this.TextField_Nombre_Usuario_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL NOMBRE DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nombre_Usuario_Registro.requestFocus();
        } else if (this.TextField_Apellido_Paterno_Usuario_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL APELLIDO PATERNO DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Apellido_Paterno_Usuario_Registro.requestFocus();
        } else if (this.TextField_Apellido_Materno_Usuario_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL APELLIDO MATERNO DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Apellido_Materno_Usuario_Registro.requestFocus();
        } else if (this.TextField_Alias_Usuario_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL ALIAS DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Alias_Usuario_Registro.requestFocus();
        } else if (this.TextField_Cedula_Usuario_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA CEDULA DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Cedula_Usuario_Registro.requestFocus();
        } else if (this.TextField_Direccion_Usuario_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA DIRECCION DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Direccion_Usuario_Registro.requestFocus();
        } else if (this.TextField_Telefono_Usuario_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL TELEFONO DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Telefono_Usuario_Registro.requestFocus();
        } else if (this.TextField_Password_Usuario_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA CONTRASENA DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Password_Usuario_Registro.requestFocus();
        }else if (this.TextField_Correo_Registro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL CORREO ELECTRONICO DEL USUARIO", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Correo_Registro.requestFocus(); 
        }else {
            try {
                int k = JOptionPane.showConfirmDialog(null, "DESEA GUARDAR LOS DATOS DEL USUARIO?", "PREGUNTA", JOptionPane.YES_NO_OPTION);
                if (k == JOptionPane.YES_OPTION) {
                    try (
                        PreparedStatement pstm = con.Conectar().prepareStatement("{call agente_registrarParticipante (?,?,?,?,?,?,?,?,?,?)}")) {
                        pstm.setString(10, TextField_Tipo_Participante_Registro.getText());
                        pstm.setString(4, TextField_Nombre_Usuario_Registro.getText());
                        pstm.setString(5, TextField_Apellido_Paterno_Usuario_Registro.getText());
                        pstm.setString(6, TextField_Apellido_Materno_Usuario_Registro.getText());
                        pstm.setString(2, TextField_Alias_Usuario_Registro.getText());
                        pstm.setString(1, TextField_Cedula_Usuario_Registro.getText());
                        pstm.setString(7, TextField_Direccion_Usuario_Registro.getText());
                        pstm.setString(8, TextField_Telefono_Usuario_Registro.getText());
                        pstm.setString(3, TextField_Password_Usuario_Registro.getText());
                        pstm.setString(9, TextField_Correo_Registro.getText());
                        //convertirlo a binarios
                        ResultSet r = pstm.executeQuery();
                        //pstm.executeUpdate();
                        System.out.println();
                        String respuesta = "";
                        while (r.next()) {
                            respuesta = r.getString(1).toString();
                        }
                        JOptionPane.showMessageDialog(null, respuesta, "CONFIRMACION", JOptionPane.WARNING_MESSAGE);

                    }
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "ERROR AL RESGISTRAR", "ERROR", JOptionPane.WARNING_MESSAGE);
                     System.out.println("Error Message: " + e.getSQLState());
                     System.out.println("SQLStateCode: "  + e.getMessage());
                     System.out.println("ErrorCode: "     + e.getErrorCode());
                }
            }
    }//GEN-LAST:event_btn_Aceptar_Usuario_RegistroActionPerformed

    private void TextField_Nombre_Usuario_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Nombre_Usuario_RegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Nombre_Usuario_RegistroActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_User_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_User_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_User_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_User_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_User_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_Alias_Usuario_Registro;
    private javax.swing.JTextField TextField_Apellido_Materno_Usuario_Registro;
    private javax.swing.JTextField TextField_Apellido_Paterno_Usuario_Registro;
    private javax.swing.JTextField TextField_Cedula_Usuario_Registro;
    private javax.swing.JTextField TextField_Correo_Registro;
    private javax.swing.JTextField TextField_Direccion_Usuario_Registro;
    private javax.swing.JTextField TextField_Nombre_Usuario_Registro;
    private javax.swing.JTextField TextField_Password_Usuario_Registro;
    private javax.swing.JTextField TextField_Telefono_Usuario_Registro;
    private javax.swing.JTextField TextField_Tipo_Participante_Registro;
    private javax.swing.JButton btn_Aceptar_Usuario_Registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lbl_Alias;
    private javax.swing.JLabel lbl_Apellido_Materno;
    private javax.swing.JLabel lbl_Apellido_Paterno;
    private javax.swing.JLabel lbl_Cedula;
    private javax.swing.JLabel lbl_Direccion;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Telefono;
    // End of variables declaration//GEN-END:variables
}
