/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views_Manager;

import conexion.conectate;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Window_Modify_Agent extends javax.swing.JFrame {

    conectate con = new conectate();
    CallableStatement cst;
    ResultSet r;
    Statement setencia;
    
    public Window_Modify_Agent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextField_ID_Agente_Modificar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextField_Nuevo_Nombre_Agente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextField_Nuevo_Ape_Paterno_Agente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextField_Nuevo_Ape_Materno_Agente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextField_Nueva_Cedula_Agente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextField_Nuevo_Alias_Agente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextField_Nueva_Direccion_Agente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TextField_Nuevo_Telefono_Agente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextField_Nuevo_Password_Agente = new javax.swing.JTextField();
        btn_Aceptar_Modificar_Agente = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_Regresar_Ventana_Acciones_Agente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite el ID del agente que desea modificar:");

        jLabel2.setText("Digite el nuevo nombre del agente:");

        jLabel3.setText("Digite el nuevo apellido paterno:");
        jLabel3.setToolTipText("");

        jLabel4.setText("Digite el nuevo apellido materno:");

        jLabel5.setText("Digite la nueva cedula:");

        jLabel6.setText("Digite el nuevo alias:");

        jLabel7.setText("Digite la nueva direccion:");

        jLabel8.setText("Digite el nuevo numero de telefono:");

        jLabel9.setText("Digite la nueva contrasena:");

        btn_Aceptar_Modificar_Agente.setText("Aceptar");
        btn_Aceptar_Modificar_Agente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Aceptar_Modificar_AgenteActionPerformed(evt);
            }
        });

        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });

        btn_Regresar_Ventana_Acciones_Agente.setText("Regresar");
        btn_Regresar_Ventana_Acciones_Agente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Regresar_Ventana_Acciones_AgenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_ID_Agente_Modificar)
                            .addComponent(TextField_Nuevo_Nombre_Agente)
                            .addComponent(TextField_Nuevo_Ape_Materno_Agente)
                            .addComponent(TextField_Nueva_Cedula_Agente)
                            .addComponent(TextField_Nuevo_Ape_Paterno_Agente, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextField_Nuevo_Password_Agente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(TextField_Nuevo_Telefono_Agente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Nueva_Direccion_Agente)
                            .addComponent(TextField_Nuevo_Alias_Agente))
                        .addGap(150, 150, 150))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btn_Aceptar_Modificar_Agente)
                .addGap(72, 72, 72)
                .addComponent(btn_Limpiar)
                .addGap(57, 57, 57)
                .addComponent(btn_Regresar_Ventana_Acciones_Agente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextField_ID_Agente_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_Nuevo_Nombre_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextField_Nuevo_Ape_Paterno_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextField_Nuevo_Ape_Materno_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TextField_Nueva_Cedula_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TextField_Nuevo_Alias_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(TextField_Nueva_Direccion_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TextField_Nuevo_Telefono_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TextField_Nuevo_Password_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar_Modificar_Agente)
                    .addComponent(btn_Limpiar)
                    .addComponent(btn_Regresar_Ventana_Acciones_Agente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Aceptar_Modificar_AgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Aceptar_Modificar_AgenteActionPerformed
        // TODO add your handling code here:
        if (this.TextField_ID_Agente_Modificar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL ID DEL AGENTE QUE DESEA MODIFICAR", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_ID_Agente_Modificar.requestFocus();
        } else if (this.TextField_Nuevo_Ape_Paterno_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL APELLIDO PATERNO DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nuevo_Ape_Paterno_Agente.requestFocus();
        } else if (this.TextField_Nuevo_Ape_Materno_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL APELLIDO MATERNO DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nuevo_Ape_Materno_Agente.requestFocus(); 
        } else if (this.TextField_Nueva_Cedula_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA CEDULA DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nueva_Cedula_Agente.requestFocus();
        } else if (this.TextField_Nuevo_Alias_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL ALIAS DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nuevo_Alias_Agente.requestFocus();
        } else if (this.TextField_Nuevo_Telefono_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL TELEFONO DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nuevo_Telefono_Agente.requestFocus();
        } else if (this.TextField_Nueva_Direccion_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA DIRECCION DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nueva_Direccion_Agente.requestFocus();
        } else if (this.TextField_Nuevo_Password_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL PASSWORD DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nuevo_Password_Agente.requestFocus(); 
        }else if (this.TextField_Nuevo_Nombre_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL NOMBRE DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nuevo_Nombre_Agente.requestFocus(); 
        } else {
            try {
                int k = JOptionPane.showConfirmDialog(null, "DESEA GUARDAR LOS DATOS DEL USUARIO?", "PREGUNTA", JOptionPane.YES_NO_OPTION);
                if (k == JOptionPane.YES_OPTION) {
                    try (
                        PreparedStatement pstm = con.Conectar().prepareStatement("{call admi_modificarAgente (?,?,?,?,?,?,?,?,?)}")) {
                        pstm.setString(2, TextField_Nueva_Cedula_Agente.getText());
                        pstm.setString(3, TextField_Nuevo_Alias_Agente.getText());
                        pstm.setString(4, TextField_Nuevo_Password_Agente.getText());
                        pstm.setString(5, TextField_Nuevo_Nombre_Agente.getText());
                        pstm.setString(6, TextField_Nuevo_Ape_Paterno_Agente.getText());
                        pstm.setString(7, TextField_Nuevo_Ape_Materno_Agente.getText());
                        pstm.setString(8, TextField_Nueva_Direccion_Agente.getText());
                        pstm.setString(9, TextField_Nuevo_Telefono_Agente.getText());
                        pstm.setString(1, TextField_ID_Agente_Modificar.getText());
                        //convertirlo a binarios
                        ResultSet r = pstm.executeQuery();
                        //pstm.executeUpdate();
                        System.out.println();
                        String respuesta = "";
                        while (r.next()) {
                            respuesta = r.getString(1).toString();
                        }
                        JOptionPane.showMessageDialog(null, respuesta, "CONFIRMACION", JOptionPane.WARNING_MESSAGE);

                    }
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "ERROR AL RESGISTRAR", "ERROR", JOptionPane.WARNING_MESSAGE);
                     System.out.println("Error Message: " + e.getSQLState());
                     System.out.println("SQLStateCode: "  + e.getMessage());
                     System.out.println("ErrorCode: "     + e.getErrorCode());
                }
            }
            
    }//GEN-LAST:event_btn_Aceptar_Modificar_AgenteActionPerformed

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        TextField_ID_Agente_Modificar.setText(null);
        TextField_Nueva_Cedula_Agente.setText(null);
        TextField_Nueva_Direccion_Agente.setText(null);
        TextField_Nuevo_Alias_Agente.setText(null);
        TextField_Nuevo_Ape_Materno_Agente.setText(null);
        TextField_Nuevo_Ape_Paterno_Agente.setText(null);
        TextField_Nuevo_Nombre_Agente.setText(null);
        TextField_Nuevo_Password_Agente.setText(null);
        TextField_Nuevo_Telefono_Agente.setText(null);
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_Regresar_Ventana_Acciones_AgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Regresar_Ventana_Acciones_AgenteActionPerformed
        // TODO add your handling code here:
        Window_Actions_Agents Ventana_Acciones_Agente = new Window_Actions_Agents();
        Ventana_Acciones_Agente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Regresar_Ventana_Acciones_AgenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Modify_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Modify_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Modify_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Modify_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Modify_Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_ID_Agente_Modificar;
    private javax.swing.JTextField TextField_Nueva_Cedula_Agente;
    private javax.swing.JTextField TextField_Nueva_Direccion_Agente;
    private javax.swing.JTextField TextField_Nuevo_Alias_Agente;
    private javax.swing.JTextField TextField_Nuevo_Ape_Materno_Agente;
    private javax.swing.JTextField TextField_Nuevo_Ape_Paterno_Agente;
    private javax.swing.JTextField TextField_Nuevo_Nombre_Agente;
    private javax.swing.JTextField TextField_Nuevo_Password_Agente;
    private javax.swing.JTextField TextField_Nuevo_Telefono_Agente;
    private javax.swing.JButton btn_Aceptar_Modificar_Agente;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Regresar_Ventana_Acciones_Agente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
