/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views_Manager;

import conexion.conectate;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Window_Suspend_Agent extends javax.swing.JFrame {

    conectate con = new conectate();
    CallableStatement cst;
    ResultSet r;
    Statement setencia;
    
    public Window_Suspend_Agent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextField_ID_Agente_Suspender = new javax.swing.JTextField();
        btn_Aceptar_Suspension_Agente = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_Regresar_Ventana_Acciones_Agentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite el ID del agente a suspender:");

        btn_Aceptar_Suspension_Agente.setText("Aceptar");
        btn_Aceptar_Suspension_Agente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Aceptar_Suspension_AgenteActionPerformed(evt);
            }
        });

        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });

        btn_Regresar_Ventana_Acciones_Agentes.setText("Regresar");
        btn_Regresar_Ventana_Acciones_Agentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Regresar_Ventana_Acciones_AgentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(TextField_ID_Agente_Suspender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Aceptar_Suspension_Agente)
                                .addGap(28, 28, 28)
                                .addComponent(btn_Limpiar)
                                .addGap(35, 35, 35)
                                .addComponent(btn_Regresar_Ventana_Acciones_Agentes))
                            .addComponent(jLabel1))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(TextField_ID_Agente_Suspender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar_Suspension_Agente)
                    .addComponent(btn_Limpiar)
                    .addComponent(btn_Regresar_Ventana_Acciones_Agentes))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Aceptar_Suspension_AgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Aceptar_Suspension_AgenteActionPerformed
        // TODO add your handling code here:
        if(this.TextField_ID_Agente_Suspender.getText().equals("")){
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL ID DEL AGENTE QUE DESEA SUSPENDER", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_ID_Agente_Suspender.requestFocus();
        }
        else{
             try {
                int k = JOptionPane.showConfirmDialog(null, "DESEA GUARDAR LOS DATOS DEL USUARIO?", "PREGUNTA", JOptionPane.YES_NO_OPTION);
                if (k == JOptionPane.YES_OPTION) {
                    try (
                        PreparedStatement pstm = con.Conectar().prepareStatement("{call admi_suspenderAgente (?)}")) {
                        pstm.setString(1, TextField_ID_Agente_Suspender.getText());
                        //convertirlo a binarios
                        ResultSet r = pstm.executeQuery();
                        //pstm.executeUpdate();
                        System.out.println();
                        String respuesta = "";
                        while (r.next()) {
                            respuesta = r.getString(1).toString();
                        }
                        JOptionPane.showMessageDialog(null, respuesta, "CONFIRMACION", JOptionPane.WARNING_MESSAGE);

                    }
                    }
            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "ERROR AL RESGISTRAR", "ERROR", JOptionPane.WARNING_MESSAGE);
                     System.out.println("Error Message: " + e.getSQLState());
                     System.out.println("SQLStateCode: "  + e.getMessage());
                     System.out.println("ErrorCode: "     + e.getErrorCode());
                }
        }
    }//GEN-LAST:event_btn_Aceptar_Suspension_AgenteActionPerformed

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        TextField_ID_Agente_Suspender.setText(null);
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_Regresar_Ventana_Acciones_AgentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Regresar_Ventana_Acciones_AgentesActionPerformed
        // TODO add your handling code here:
        Window_Actions_Agents Ventana_Acciones_Agente = new Window_Actions_Agents();
        this.setVisible(false);
        Ventana_Acciones_Agente.setVisible(true);
    }//GEN-LAST:event_btn_Regresar_Ventana_Acciones_AgentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Suspend_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Suspend_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Suspend_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Suspend_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Suspend_Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_ID_Agente_Suspender;
    private javax.swing.JButton btn_Aceptar_Suspension_Agente;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Regresar_Ventana_Acciones_Agentes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
