/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views_Manager;

import conexion.conectate;
import java.awt.Window;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Window_New_Agent extends javax.swing.JFrame {

    conectate con = new conectate();
    CallableStatement cst;
    ResultSet r;
    Statement setencia;
    
    public Window_New_Agent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextField_Nombre_Nuevo_Agente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextField_Ape_Paterno_Nuevo_Agente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextField_Ape_Materno_Nuevo_Agente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextField_Cedula_Nuevo_Agente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextField_Alias_Nuevo_Agente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextField_Telef_Nuevo_Agente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextField_Direccion_Nuevo_Agente = new javax.swing.JTextField();
        lbl_Password_Nuevo_Agente = new javax.swing.JLabel();
        TextField_Password_Nuevo_Agente = new javax.swing.JTextField();
        btn_Aceptar_Nuevo_Agente = new javax.swing.JButton();
        btn_Limpar_Nuevo_Agente = new javax.swing.JButton();
        btn_Regresar_Ventana_Acciones_Agente = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido Paterno");
        jLabel2.setToolTipText("");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Cedula");

        jLabel5.setText("Alias");

        jLabel6.setText("Telefono");

        jLabel7.setText("Direccion");

        lbl_Password_Nuevo_Agente.setText("Password");

        btn_Aceptar_Nuevo_Agente.setText("Aceptar");
        btn_Aceptar_Nuevo_Agente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Aceptar_Nuevo_AgenteActionPerformed(evt);
            }
        });

        btn_Limpar_Nuevo_Agente.setText("Limpiar");
        btn_Limpar_Nuevo_Agente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Limpar_Nuevo_AgenteActionPerformed(evt);
            }
        });

        btn_Regresar_Ventana_Acciones_Agente.setText("Regresar");
        btn_Regresar_Ventana_Acciones_Agente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Regresar_Ventana_Acciones_AgenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextField_Nombre_Nuevo_Agente)
                                    .addComponent(TextField_Ape_Paterno_Nuevo_Agente, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(lbl_Password_Nuevo_Agente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_Ape_Materno_Nuevo_Agente)
                                    .addComponent(TextField_Cedula_Nuevo_Agente)
                                    .addComponent(TextField_Alias_Nuevo_Agente)
                                    .addComponent(TextField_Telef_Nuevo_Agente)
                                    .addComponent(TextField_Direccion_Nuevo_Agente)
                                    .addComponent(TextField_Password_Nuevo_Agente, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btn_Aceptar_Nuevo_Agente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Limpar_Nuevo_Agente)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Regresar_Ventana_Acciones_Agente)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextField_Nombre_Nuevo_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_Ape_Paterno_Nuevo_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextField_Ape_Materno_Nuevo_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextField_Cedula_Nuevo_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextField_Alias_Nuevo_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TextField_Telef_Nuevo_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextField_Direccion_Nuevo_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Password_Nuevo_Agente)
                    .addComponent(TextField_Password_Nuevo_Agente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar_Nuevo_Agente)
                    .addComponent(btn_Limpar_Nuevo_Agente)
                    .addComponent(btn_Regresar_Ventana_Acciones_Agente))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Aceptar_Nuevo_AgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Aceptar_Nuevo_AgenteActionPerformed
        // TODO add your handling code here:
        if (this.TextField_Nombre_Nuevo_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL NOMBRE DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nombre_Nuevo_Agente.requestFocus();
        } else if (this.TextField_Ape_Paterno_Nuevo_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL APELLIDO PATERNO DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Ape_Paterno_Nuevo_Agente.requestFocus();
        } else if (this.TextField_Ape_Materno_Nuevo_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL APELLIDO MATERNO DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Ape_Materno_Nuevo_Agente.requestFocus(); 
        } else if (this.TextField_Cedula_Nuevo_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA CEDULA DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Cedula_Nuevo_Agente.requestFocus();
        } else if (this.TextField_Alias_Nuevo_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL ALIAS DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Alias_Nuevo_Agente.requestFocus();
        } else if (this.TextField_Telef_Nuevo_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL TELEFONO DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Telef_Nuevo_Agente.requestFocus();
        } else if (this.TextField_Direccion_Nuevo_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA DIRECCION DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Direccion_Nuevo_Agente.requestFocus();
        } else if (this.TextField_Password_Nuevo_Agente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL PASSWORD DEL AGENTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Password_Nuevo_Agente.requestFocus(); 
        } else {
            try {
                int k = JOptionPane.showConfirmDialog(null, "DESEA GUARDAR LOS DATOS DEL USUARIO?", "PREGUNTA", JOptionPane.YES_NO_OPTION);
                if (k == JOptionPane.YES_OPTION) {
                    try (
                        PreparedStatement pstm = con.Conectar().prepareStatement("{call admi_crearAgente (?,?,?,?,?,?,?,?)}")) {
                        pstm.setString(1, TextField_Cedula_Nuevo_Agente.getText());
                        pstm.setString(2, TextField_Alias_Nuevo_Agente.getText());
                        pstm.setString(3, TextField_Password_Nuevo_Agente.getText());
                        pstm.setString(4, TextField_Nombre_Nuevo_Agente.getText());
                        pstm.setString(5, TextField_Ape_Paterno_Nuevo_Agente.getText());
                        pstm.setString(6, TextField_Ape_Materno_Nuevo_Agente.getText());
                        pstm.setString(7, TextField_Direccion_Nuevo_Agente.getText());
                        pstm.setString(8, TextField_Telef_Nuevo_Agente.getText());
                        //convertirlo a binarios
                        ResultSet r = pstm.executeQuery();
                        //pstm.executeUpdate();
                        System.out.println();
                        String respuesta = "";
                        while (r.next()) {
                            respuesta = r.getString(1).toString();
                        }
                        JOptionPane.showMessageDialog(null, respuesta, "CONFIRMACION", JOptionPane.WARNING_MESSAGE);

                    }
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "ERROR AL RESGISTRAR", "ERROR", JOptionPane.WARNING_MESSAGE);
                     System.out.println("Error Message: " + e.getSQLState());
                     System.out.println("SQLStateCode: "  + e.getMessage());
                     System.out.println("ErrorCode: "     + e.getErrorCode());
                }
            }
            
    }//GEN-LAST:event_btn_Aceptar_Nuevo_AgenteActionPerformed

    private void btn_Limpar_Nuevo_AgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Limpar_Nuevo_AgenteActionPerformed
        // TODO add your handling code here:
        TextField_Nombre_Nuevo_Agente.setText(null);
        TextField_Ape_Materno_Nuevo_Agente.setText(null);
        TextField_Ape_Paterno_Nuevo_Agente.setText(null);
        TextField_Alias_Nuevo_Agente.setText(null);
        TextField_Direccion_Nuevo_Agente.setText(null);
        TextField_Password_Nuevo_Agente.setText(null);
        TextField_Telef_Nuevo_Agente.setText(null);
        TextField_Cedula_Nuevo_Agente.setText(null);
    }//GEN-LAST:event_btn_Limpar_Nuevo_AgenteActionPerformed

    private void btn_Regresar_Ventana_Acciones_AgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Regresar_Ventana_Acciones_AgenteActionPerformed
        // TODO add your handling code here:
        Window_Actions_Agents Ventana_Acciones_Agente = new Window_Actions_Agents();
        this.setVisible(false);
        Ventana_Acciones_Agente.setVisible(true);
        
    }//GEN-LAST:event_btn_Regresar_Ventana_Acciones_AgenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_New_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_New_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_New_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_New_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_New_Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_Alias_Nuevo_Agente;
    private javax.swing.JTextField TextField_Ape_Materno_Nuevo_Agente;
    private javax.swing.JTextField TextField_Ape_Paterno_Nuevo_Agente;
    private javax.swing.JTextField TextField_Cedula_Nuevo_Agente;
    private javax.swing.JTextField TextField_Direccion_Nuevo_Agente;
    private javax.swing.JTextField TextField_Nombre_Nuevo_Agente;
    private javax.swing.JTextField TextField_Password_Nuevo_Agente;
    private javax.swing.JTextField TextField_Telef_Nuevo_Agente;
    private javax.swing.JButton btn_Aceptar_Nuevo_Agente;
    private javax.swing.JButton btn_Limpar_Nuevo_Agente;
    private javax.swing.JButton btn_Regresar_Ventana_Acciones_Agente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_Password_Nuevo_Agente;
    // End of variables declaration//GEN-END:variables
}
