/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views_Manager;

/**
 *
 * @author Daniel
 */
public class Window_Manager extends javax.swing.JFrame {

    /**
     * Creates new form Window_Manager
     */
    public Window_Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Acciones_Agentes_Administrador = new javax.swing.JButton();
        btn_Listar_Subastas_Administrador = new javax.swing.JButton();
        btn_Listar_Historial_Subastas_Administrador = new javax.swing.JButton();
        btn_Listar_Historial_Subastas_Usuarios_Administrador = new javax.swing.JButton();
        btn_Listar_Historial_Ofertas_Ganadoras_Usuario_Administrador = new javax.swing.JButton();
        btn_Modificar_Comision_Administrador = new javax.swing.JButton();
        btn_Modificar_Monto_Oferta_Administrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Acciones_Agentes_Administrador.setText("Acciones sobre Agentes");

        btn_Listar_Subastas_Administrador.setText("Listar Subastas");

        btn_Listar_Historial_Subastas_Administrador.setText("Listar Historial de ofertas por Subasta ");
        btn_Listar_Historial_Subastas_Administrador.setToolTipText("");

        btn_Listar_Historial_Subastas_Usuarios_Administrador.setText("Listar Historial de Subastas por Usuario");

        btn_Listar_Historial_Ofertas_Ganadoras_Usuario_Administrador.setText("Listar Historial de ofertas ganadoras por Usuario");

        btn_Modificar_Comision_Administrador.setText("Modificar Comision por Subasta");

        btn_Modificar_Monto_Oferta_Administrador.setText("Modificar monto minimo de oferta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Acciones_Agentes_Administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listar_Subastas_Administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listar_Historial_Subastas_Administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listar_Historial_Subastas_Usuarios_Administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listar_Historial_Ofertas_Ganadoras_Usuario_Administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Modificar_Comision_Administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Modificar_Monto_Oferta_Administrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_Acciones_Agentes_Administrador)
                .addGap(18, 18, 18)
                .addComponent(btn_Listar_Subastas_Administrador)
                .addGap(18, 18, 18)
                .addComponent(btn_Listar_Historial_Subastas_Administrador)
                .addGap(18, 18, 18)
                .addComponent(btn_Listar_Historial_Subastas_Usuarios_Administrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Listar_Historial_Ofertas_Ganadoras_Usuario_Administrador)
                .addGap(18, 18, 18)
                .addComponent(btn_Modificar_Comision_Administrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Modificar_Monto_Oferta_Administrador)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Acciones_Agentes_Administrador;
    private javax.swing.JButton btn_Listar_Historial_Ofertas_Ganadoras_Usuario_Administrador;
    private javax.swing.JButton btn_Listar_Historial_Subastas_Administrador;
    private javax.swing.JButton btn_Listar_Historial_Subastas_Usuarios_Administrador;
    private javax.swing.JButton btn_Listar_Subastas_Administrador;
    private javax.swing.JButton btn_Modificar_Comision_Administrador;
    private javax.swing.JButton btn_Modificar_Monto_Oferta_Administrador;
    // End of variables declaration//GEN-END:variables
}
