/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Agent;

import conexion.conectate;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Window_Suspend_User extends javax.swing.JFrame {

     conectate con = new conectate();
    CallableStatement cst;
    ResultSet r;
    Statement setencia;
    
    public Window_Suspend_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextField_ID_Participante_Suspender = new javax.swing.JTextField();
        btn_Aceptar_Participante_Suspender = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_Regresar_Ventana_Agente = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite el ID del participante a suspender:");

        btn_Aceptar_Participante_Suspender.setText("Aceptar");
        btn_Aceptar_Participante_Suspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Aceptar_Participante_SuspenderActionPerformed(evt);
            }
        });

        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });

        btn_Regresar_Ventana_Agente.setText("Regresar");
        btn_Regresar_Ventana_Agente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Regresar_Ventana_AgenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Aceptar_Participante_Suspender)
                                .addGap(30, 30, 30)
                                .addComponent(btn_Limpiar)
                                .addGap(34, 34, 34)
                                .addComponent(btn_Regresar_Ventana_Agente))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(TextField_ID_Participante_Suspender, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(TextField_ID_Participante_Suspender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar_Participante_Suspender)
                    .addComponent(btn_Limpiar)
                    .addComponent(btn_Regresar_Ventana_Agente))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Aceptar_Participante_SuspenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Aceptar_Participante_SuspenderActionPerformed
        // TODO add your handling code here:
        if(this.TextField_ID_Participante_Suspender.getText().equals("")){
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL ID DEL PARTICIPANTE QUE DESEA SUSPENDER", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_ID_Participante_Suspender.requestFocus();
        }
        else{
             try {
                int k = JOptionPane.showConfirmDialog(null, "DESEA GUARDAR LOS DATOS DEL USUARIO?", "PREGUNTA", JOptionPane.YES_NO_OPTION);
                if (k == JOptionPane.YES_OPTION) {
                    try (
                        PreparedStatement pstm = con.Conectar().prepareStatement("{call agente_suspenderParticipante (?)}")) {
                        pstm.setString(1, TextField_ID_Participante_Suspender.getText());
                        //convertirlo a binarios
                        ResultSet r = pstm.executeQuery();
                        //pstm.executeUpdate();
                        System.out.println();
                        String respuesta = "";
                        while (r.next()) {
                            respuesta = r.getString(1).toString();
                        }
                        JOptionPane.showMessageDialog(null, respuesta, "CONFIRMACION", JOptionPane.WARNING_MESSAGE);

                    }
                    }
            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "ERROR AL RESGISTRAR", "ERROR", JOptionPane.WARNING_MESSAGE);
                     System.out.println("Error Message: " + e.getSQLState());
                     System.out.println("SQLStateCode: "  + e.getMessage());
                     System.out.println("ErrorCode: "     + e.getErrorCode());
                }
        }
    }//GEN-LAST:event_btn_Aceptar_Participante_SuspenderActionPerformed

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        TextField_ID_Participante_Suspender.setText(null);
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_Regresar_Ventana_AgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Regresar_Ventana_AgenteActionPerformed
        // TODO add your handling code here:
        Window_Actions_User Ventana_Acciones_Participante = new Window_Actions_User();
        this.setVisible(false);
        Ventana_Acciones_Participante.setVisible(true);
    }//GEN-LAST:event_btn_Regresar_Ventana_AgenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Suspend_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Suspend_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Suspend_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Suspend_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Suspend_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_ID_Participante_Suspender;
    private javax.swing.JButton btn_Aceptar_Participante_Suspender;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Regresar_Ventana_Agente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
