/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Agent;

/**
 *
 * @author Daniel
 */
public class Window_Actions_User extends javax.swing.JFrame {

    /**
     * Creates new form Window_Actions_User
     */
    public Window_Actions_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Modificar_Participante = new javax.swing.JButton();
        btn_Suspender_Participantes = new javax.swing.JButton();
        Btn_Reactivar_Participante = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Modificar_Participante.setText("Modificar");

        btn_Suspender_Participantes.setText("Suspender");
        btn_Suspender_Participantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Suspender_ParticipantesActionPerformed(evt);
            }
        });

        Btn_Reactivar_Participante.setText("Reactivar");
        Btn_Reactivar_Participante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reactivar_ParticipanteActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Suspender_Participantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Modificar_Participante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Reactivar_Participante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btn_Modificar_Participante)
                .addGap(36, 36, 36)
                .addComponent(btn_Suspender_Participantes)
                .addGap(34, 34, 34)
                .addComponent(Btn_Reactivar_Participante)
                .addGap(39, 39, 39)
                .addComponent(btnRegresar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Suspender_ParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Suspender_ParticipantesActionPerformed
        // TODO add your handling code here:
        Window_Suspend_User Ventana_Suspender_Participante = new Window_Suspend_User();
        this.setVisible(false);
        Ventana_Suspender_Participante.setVisible(true);
    }//GEN-LAST:event_btn_Suspender_ParticipantesActionPerformed

    private void Btn_Reactivar_ParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reactivar_ParticipanteActionPerformed
        // TODO add your handling code here:
        Window_Enable_User Ventana_Habilitar_Participante = new Window_Enable_User();
        this.dispose();
        Ventana_Habilitar_Participante.setVisible(true);
    }//GEN-LAST:event_Btn_Reactivar_ParticipanteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Window_Agent Ventana_Agente = new Window_Agent();
        Ventana_Agente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Actions_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Actions_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Actions_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Actions_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Actions_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Reactivar_Participante;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btn_Modificar_Participante;
    private javax.swing.JButton btn_Suspender_Participantes;
    // End of variables declaration//GEN-END:variables
}
