/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Agent;

import conexion.conectate;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Window_New_User extends javax.swing.JFrame {

    conectate con = new conectate();
    CallableStatement cst;
    ResultSet r;
    Statement setencia;
    
    
    public Window_New_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextField_Nombre_Nuevo_Particpante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextField_Apellido_Pat_Participante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextField_ApellidoM_Participante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Aceptar_Nuevo_Participante = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_Regresar_Ventana_Agente = new javax.swing.JButton();
        TextField_Cedula_Participante = new javax.swing.JTextField();
        TextField_Alias_Participante = new javax.swing.JTextField();
        TextField_Direccion_Participante = new javax.swing.JTextField();
        TextField_Telefono_Participante = new javax.swing.JTextField();
        TextField_Correo_Participante = new javax.swing.JTextField();
        TextField_Password_Participante = new javax.swing.JTextField();
        TextField_Tipo_Participante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del Participante:");

        jLabel2.setText("Apellido paterno:");

        jLabel3.setText("Apellido materno:");

        jLabel4.setText("Cedula:");

        jLabel5.setText("Alias:");

        jLabel6.setText("Direccion:");

        jLabel7.setText("Telefono:");

        jLabel8.setText("Correo electronico:");

        jLabel9.setText("Password:");

        jLabel10.setText("Tipo de Participante (V o C):");

        btn_Aceptar_Nuevo_Participante.setText("Aceptar");
        btn_Aceptar_Nuevo_Participante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Aceptar_Nuevo_ParticipanteActionPerformed(evt);
            }
        });

        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });

        btn_Regresar_Ventana_Agente.setText("Regresar");
        btn_Regresar_Ventana_Agente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Regresar_Ventana_AgenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Aceptar_Nuevo_Participante)
                        .addGap(53, 53, 53)
                        .addComponent(btn_Limpiar)
                        .addGap(43, 43, 43)
                        .addComponent(btn_Regresar_Ventana_Agente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_Tipo_Participante))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_Apellido_Pat_Participante, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(TextField_Nombre_Nuevo_Particpante, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(TextField_ApellidoM_Participante, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(TextField_Cedula_Participante)
                            .addComponent(TextField_Alias_Participante)
                            .addComponent(TextField_Direccion_Participante)
                            .addComponent(TextField_Telefono_Participante)
                            .addComponent(TextField_Correo_Participante)
                            .addComponent(TextField_Password_Participante))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextField_Nombre_Nuevo_Particpante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_Apellido_Pat_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextField_ApellidoM_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextField_Cedula_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextField_Alias_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TextField_Direccion_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextField_Telefono_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(TextField_Correo_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TextField_Password_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TextField_Tipo_Participante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Aceptar_Nuevo_Participante)
                    .addComponent(btn_Limpiar)
                    .addComponent(btn_Regresar_Ventana_Agente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Aceptar_Nuevo_ParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Aceptar_Nuevo_ParticipanteActionPerformed
        // TODO add your handling code here:
         if (this.TextField_Nombre_Nuevo_Particpante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL NOMBRE DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Nombre_Nuevo_Particpante.requestFocus();
        } else if (this.TextField_Apellido_Pat_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL APELLIDO PATERNO DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Apellido_Pat_Participante.requestFocus();
        } else if (this.TextField_ApellidoM_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL APELLIDO MATERNO DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_ApellidoM_Participante.requestFocus(); 
        } else if (this.TextField_Cedula_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA CEDULA DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Cedula_Participante.requestFocus();
        } else if (this.TextField_Alias_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL ALIAS DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Alias_Participante.requestFocus();
        } else if (this.TextField_Telefono_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL TELEFONO DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Telefono_Participante.requestFocus();
        } else if (this.TextField_Direccion_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR LA DIRECCION DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Direccion_Participante.requestFocus();
        } else if (this.TextField_Password_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL PASSWORD DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Password_Participante.requestFocus(); 
        } else if (this.TextField_Tipo_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL TIPO DE PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Tipo_Participante.requestFocus();  
        } else if (this.TextField_Correo_Participante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR EL CORREO DEL PARTICIPANTE", "VERIFICAR", JOptionPane.WARNING_MESSAGE);
            this.TextField_Correo_Participante.requestFocus(); 
        } else {
            try {
                int k = JOptionPane.showConfirmDialog(null, "DESEA GUARDAR LOS DATOS DEL PARTICIPANTE?", "PREGUNTA", JOptionPane.YES_NO_OPTION);
                if (k == JOptionPane.YES_OPTION) {
                    try (
                        PreparedStatement pstm = con.Conectar().prepareStatement("{call agente_registrarParticipante (?,?,?,?,?,?,?,?,?,?)}")) {
                        pstm.setString(1, TextField_Cedula_Participante.getText());
                        pstm.setString(2, TextField_Alias_Participante.getText());
                        pstm.setString(3, TextField_Password_Participante.getText());
                        pstm.setString(4, TextField_Nombre_Nuevo_Particpante.getText());
                        pstm.setString(5, TextField_Apellido_Pat_Participante.getText());
                        pstm.setString(6, TextField_ApellidoM_Participante.getText());
                        pstm.setString(7, TextField_Direccion_Participante.getText());
                        pstm.setString(8, TextField_Telefono_Participante.getText());
                        pstm.setString(10, TextField_Tipo_Participante.getText());
                        pstm.setString(9, TextField_Correo_Participante.getText());
                        //convertirlo a binarios
                        ResultSet r = pstm.executeQuery();
                        //pstm.executeUpdate();
                        System.out.println();
                        String respuesta = "";
                        while (r.next()) {
                            respuesta = r.getString(1).toString();
                        }
                        JOptionPane.showMessageDialog(null, respuesta, "CONFIRMACION", JOptionPane.WARNING_MESSAGE);

                    }
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "ERROR AL RESGISTRAR", "ERROR", JOptionPane.WARNING_MESSAGE);
                     System.out.println("Error Message: " + e.getSQLState());
                     System.out.println("SQLStateCode: "  + e.getMessage());
                     System.out.println("ErrorCode: "     + e.getErrorCode());
                }
            }
            
    }//GEN-LAST:event_btn_Aceptar_Nuevo_ParticipanteActionPerformed

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        // TODO add your handling code here:
        TextField_Alias_Participante.setText(null);
        TextField_ApellidoM_Participante.setText(null);
        TextField_Apellido_Pat_Participante.setText(null);
        TextField_Cedula_Participante.setText(null);
        TextField_Correo_Participante.setText(null);
        TextField_Direccion_Participante.setText(null);
        TextField_Nombre_Nuevo_Particpante.setText(null);
        TextField_Password_Participante.setText(null);
        TextField_Telefono_Participante.setText(null);
        TextField_Tipo_Participante.setText(null);
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_Regresar_Ventana_AgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Regresar_Ventana_AgenteActionPerformed
        // TODO add your handling code here:
            Window_Agent Ventana_Agente = new Window_Agent();
            this.setVisible(false);
            Ventana_Agente.setVisible(true);
    }//GEN-LAST:event_btn_Regresar_Ventana_AgenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_New_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_Alias_Participante;
    private javax.swing.JTextField TextField_ApellidoM_Participante;
    private javax.swing.JTextField TextField_Apellido_Pat_Participante;
    private javax.swing.JTextField TextField_Cedula_Participante;
    private javax.swing.JTextField TextField_Correo_Participante;
    private javax.swing.JTextField TextField_Direccion_Participante;
    private javax.swing.JTextField TextField_Nombre_Nuevo_Particpante;
    private javax.swing.JTextField TextField_Password_Participante;
    private javax.swing.JTextField TextField_Telefono_Participante;
    private javax.swing.JTextField TextField_Tipo_Participante;
    private javax.swing.JButton btn_Aceptar_Nuevo_Participante;
    private javax.swing.JButton btn_Limpiar;
    javax.swing.JButton btn_Regresar_Ventana_Agente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
