/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Agent;

/**
 *
 * @author Daniel
 */
public class Window_Agent extends javax.swing.JFrame {

    /**
     * Creates new form Window_Agent
     */
    public Window_Agent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistar_Nuevos_Participantes = new javax.swing.JButton();
        btn_Agregar_Tarjeta_Credito = new javax.swing.JButton();
        btn_Acciones_Sobre_Partcipante = new javax.swing.JButton();
        btn_Listar_Subastas_Agente = new javax.swing.JButton();
        btn_Listar_Historial_Ofertas_Subasta = new javax.swing.JButton();
        btn_Listar_Historial_Subastas_Usuario = new javax.swing.JButton();
        btn_Listar_Ofertas_Ganadoras_Usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistar_Nuevos_Participantes.setText("Registar Nuevos Participantes");

        btn_Agregar_Tarjeta_Credito.setText("Agregar Tarjeta de Credito");

        btn_Acciones_Sobre_Partcipante.setText("Acciones sobre un Participante");

        btn_Listar_Subastas_Agente.setText("Listar Subastas");

        btn_Listar_Historial_Ofertas_Subasta.setText("Historial de ofertas por Subasta");

        btn_Listar_Historial_Subastas_Usuario.setText("Historial de Subastas por Usuario");

        btn_Listar_Ofertas_Ganadoras_Usuario.setText("Historial de ofertas ganadoras de un usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistar_Nuevos_Participantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Agregar_Tarjeta_Credito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Acciones_Sobre_Partcipante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listar_Subastas_Agente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listar_Historial_Ofertas_Subasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listar_Historial_Subastas_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Listar_Ofertas_Ganadoras_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnRegistar_Nuevos_Participantes)
                .addGap(18, 18, 18)
                .addComponent(btn_Agregar_Tarjeta_Credito)
                .addGap(18, 18, 18)
                .addComponent(btn_Acciones_Sobre_Partcipante)
                .addGap(18, 18, 18)
                .addComponent(btn_Listar_Subastas_Agente)
                .addGap(18, 18, 18)
                .addComponent(btn_Listar_Historial_Ofertas_Subasta)
                .addGap(18, 18, 18)
                .addComponent(btn_Listar_Historial_Subastas_Usuario)
                .addGap(18, 18, 18)
                .addComponent(btn_Listar_Ofertas_Ganadoras_Usuario)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window_Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar_Nuevos_Participantes;
    private javax.swing.JButton btn_Acciones_Sobre_Partcipante;
    private javax.swing.JButton btn_Agregar_Tarjeta_Credito;
    private javax.swing.JButton btn_Listar_Historial_Ofertas_Subasta;
    private javax.swing.JButton btn_Listar_Historial_Subastas_Usuario;
    private javax.swing.JButton btn_Listar_Ofertas_Ganadoras_Usuario;
    private javax.swing.JButton btn_Listar_Subastas_Agente;
    // End of variables declaration//GEN-END:variables
}
